/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include "stm32f4xx.h"
#include "system_stm32f4xx.h"
#include "uart.h"
#include "led.h"
#include "wdt.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void) {
		char str[32];
		LedInit(LED_RED);

		if(IsWdtReset())
		{
			while(1){
				LedBlink(LED_RED, 200);
				DelayMs(200);
			}
		}

		LedInit(LED_ORANGE);
		LedInit(LED_GREEN);
		UartInit(9600);
		UartPuts("HELLO DESD\r\n");
		UartPuts("Watchdog Timer Demo \r \n");
		WdtInit(10000);
		while(1)
		{
			LedOn(LED_ORANGE);
			UartGets(str);
			LedOff(LED_ORANGE);
			LedOn(LED_GREEN);
			strupr(str);
			UartPuts(str);
			LedOff(LED_GREEN);
			WdtFeed();
		}
	return 0;
}





