/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include "stm32f4xx.h"
#include "led.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

volatile uint32_t  xTicks=0;
//Handle Systick interrupt
void SysTick_Handler(void)
{
		xTicks++;
}

void SysTick_DelayMs(uint32_t ms)
{
	//get current number of ticks
	uint32_t curTicks =xTicks;
	//wait for "ms" more ticks (1 tick per ms)
	uint32_t waitTill = curTicks + ms;
	while (xTicks < waitTill)
		;
}

int main(void) {


	LedInit(LED_RED);
	SysTick_Config(SystemCoreClock /1000);
	while(1)
	{
		LedToggle(LED_RED);
		SysTick_DelayMs(1000);
	}
	return 0;

}





