/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "adc.h"
#include "lcd.h"
#include "switch.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void) {

	AdcInit();
	LcdInit();
	switch_init(SWITCH_PIN);

	while(1)
	{

		char str[20];
		uint16_t val= AdcRead();
		if(switch_status()==1)
		{
			sprintf(str,"ADC=%d",val);
			LcdPuts(LCD_LINE1, str);
			DelayMs(300);
	}
	}	return 0;


}


