/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include "uart.h"
#include "led.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	char str[16];
	UartInit(9600);
	UartPuts("Enter Strings\r\n");
/*	uint8_t arr[] = {LED_GREEN, LED_ORANGE, LED_RED, LED_BLUE};
			for(uint8_t i = 0 ; i < 4 ; i++)
				led_init(arr[i]);
			char ch='A';
	*/
	while(1)
	{
		UartGets(str);
	/*	if(! strcmp((char)ch,str))
		{
			led_toggle(arr[1]);
		}
	*/
		UartPuts(str);
	}
}

