/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "accel.h"
#include "uart.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	char str[32];
	AccelData_t accel;
	UartInit(9600);
	UartPuts("SPI Accel Demo!!\r\n");
	AccelInit();
	while(AccelWaitForChange()) {
		AccelRead(&accel);
		sprintf(str, "X=%d, Y=%d, Z=%d\r\n", accel.x, accel.y, accel.z);
		UartPuts(str);
		DelayMs(1000);
	}
}

